#!/usr/bin/env python3
"""Regenerate the roster table in BENCHMARK.md from the benchmark manifest and
progress/history.csv (latest win rate per external opponent -> tier)."""
import csv, re
from collections import defaultdict
from pathlib import Path
REPO = Path(__file__).resolve().parent.parent
MANIFEST = Path.home() / "projects/vibe/bc21-benchmarks/manifest.tsv"

def tier(pct, prev_solved):
    if pct is None: return "untested"
    if pct < 20: return "locked"
    if pct < 50: return "target"
    if pct <= 90: return "peer"
    return "solved" if prev_solved else "peer(>90 once)"

def main():
    rows = list(csv.DictReader(open(MANIFEST), delimiter="\t"))
    hist = defaultdict(list)
    hp = REPO / "progress" / "history.csv"
    if hp.is_file():
        for r in csv.DictReader(open(hp)): hist[r["opponent"]].append((r["date"], float(r["win_pct"]), int(r["total"])))
    lines = ["| opponent | repo (commit) | last win % | games | tier | history |", "|---|---|---|---|---|---|"]
    by_repo = defaultdict(int)
    for r in rows: by_repo[r["repo"]] += 1
    for r in sorted(rows, key=lambda r: (r["repo"], r["name"])):
        h = sorted(hist.get(r["name"], []))
        last = h[-1] if h else None
        prev_solved = len(h) >= 2 and h[-2][1] > 90
        pct = f"{last[1]:.0f}" if last else "-"
        games = str(last[2]) if last else "-"
        trend = " ".join(f"{x[1]:.0f}" for x in h[-6:]) if h else ""
        lines.append(f"| `{r['name']}` | {r['repo']} ({r['commit']}) | {pct} | {games} | {tier(last[1] if last else None, prev_solved)} | {trend} |")
    table = "\n".join(lines) + f"\n\n{len(rows)} bot packages from {len(by_repo)} repositories.\n"
    bm = REPO / "BENCHMARK.md"; s = bm.read_text()
    marker = "<!-- ROSTER TABLE: regenerated by tools/bench-roster.py -->"
    s = s[: s.index(marker) + len(marker)] + "\n\n" + table
    bm.write_text(s); print(f"BENCHMARK.md roster: {len(rows)} packages, {sum(1 for r in rows if hist.get(r['name']))} with results")

if __name__ == "__main__": main()
